"""Pack project-owned PBM artwork into flash-only C++ arrays (stdlib only)."""
from pathlib import Path
import re


def build(project):
    root = Path(project)
    files = sorted((root / 'data/habit_sheep/art').glob('*.pbm'))
    lines = ['// Generated by scripts/build_habit_art.py. Do not edit.', '#pragma once',
             '#include <cstdint>', 'namespace habitArt {',
             'struct Bitmap { const uint8_t* data; uint16_t width, height; };']
    for path in files:
        raw = path.read_bytes()
        match = re.match(rb'P4\s+(\d+)\s+(\d+)\s', raw)
        if not match:
            raise ValueError(f'Invalid PBM: {path}')
        width, height = map(int, match.groups())
        data = raw[match.end():]
        assert len(data) == ((width + 7) // 8) * height
        name = path.stem
        lines.append(f'inline constexpr uint8_t {name}Data[] = {{')
        for offset in range(0, len(data), 24):
            lines.append('  ' + ','.join(f'0x{x:02x}' for x in data[offset:offset + 24]) + ',')
        lines.extend(['};', f'inline constexpr Bitmap {name}{{{name}Data, {width}, {height}}};'])
    lines.append('}  // namespace habitArt')
    output = root / 'src/components/icons/habitArt.generated.h'
    text = '\n'.join(lines) + '\n'
    if not output.exists() or output.read_text() != text:
        output.write_text(text)


if __name__ == '__main__':
    build(Path(__file__).resolve().parent.parent)
else:
    Import('env')
    build(env['PROJECT_DIR'])
